### ISSUE TITLE
I can only capture 'send' package

### ISSUE THREAD

**Issue by Illyasviels** [karashiiro/node-machina-ffxiv#23]
```
Machina.on('raw', (content) => {
    console.log(content)
});
```

For this, I can only get the operation === 'send' packages. I cant get any 'receive' packages.
For example:

```
{
  type: 'pingHandler',
  opcode: 101,
  region: 'CN',
  connection: '192.168.1.9:54678=>109.244.5.40:54993',
  operation: 'send',
  epoch: 1577974664720,
  packetSize: 56,
  segmentType: 3,
  sourceActorSessionID: 15446963,
  targetActorSessionID: 15446963,
  serverID: 830,
  timestamp: 9510732,
  data: Uint8Array [
    76, 31, 145, 0, 0, 0, 0, 0,
     0,  0,   0, 0, 0, 0, 0, 0,
     0,  0,   0, 0, 0, 0, 0, 0
  ]
}
```

**Comment by karashiiro** [comment]
You need to explicitly allow the exe through your firewall to get inbound packets. On Windows 10, you should be able to get there from the button on the taskbar, then going to Windows Firewall Settings and clicking “Allow an app through Windows Firewall”. Link up the exe in `node_modules/node-machina-ffxiv/MachinaWrapper` and it should work.

**Comment by Illyasviels** [comment]
Thanks, resolved it!
